### ISSUE TITLE
Question: Beforeall & Afterall Not Working Properly

### ISSUE THREAD

**Issue by satyabrat105** [vitalets/playwright-bdd#216]
In my project , i have one featurefile, 7 scenarios. in hooks i am using beforeall,before,after,afterall. when i executed the featurefile,  before every scenario it is executing beforeall and after complete the scenario it executed afterall. 7times it executed beforeall and afterall. am i doing wrong?  plaese share your feedback .

**Comment by farnsword-ok** [comment]
`Also note that BeforeAll / AfterAll are called in each worker `
How can I ensure the whole featurefile is executed on the same worker?
Basically, I need to have a precondition for the featurefile, so it executes only once for this particular featurefile, but not for any other featurefile.

**Comment by maxtuzz** [comment]
@farnsword-ok You can declaratively achieve that with a background applied to a single feature file:

```
Feature:  My Feature
  Background:
    Given I am logged in as 'a-user-with-specific-roles'

  Scenario: 1..
  Scenario: 2..
  Scenario: 3..
```
